# 동시 접속 처리에 대한 설정 (보통 기본값 사용)
events {}

# 웹 트래픽(HTTP)에 대한 설정 시작
http {
    # 1. 파일 형식 정의 (CSS, JS 등이 정상적으로 로드되게 함)
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    
    server {
        listen 80;

        # 2. 리액트 정적 파일 설정
        # 브라우저에 주소를 입력하면 /usr/share/nginx/html에 있는 index.html을 보여줍니다.
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html; # 리액트 라우팅(URL 이동)을 위한 설정
        }

        location /api {
            proxy_pass http://app:8080; # 'app'은 컴포즈의 서비스 이름
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}